# Generated by Django 4.2 on 2024-09-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='codigo',
            new_name='id_DetallePedido',
        ),
    ]
