# Generated by Django 4.2 on 2025-05-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipoProducto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
