# Generated by Django 4.2 on 2024-09-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoProducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoCultivo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=32)),
                ('FechaSiembra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.SmallIntegerField()),
                ('tipoProductoId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TipoProducto.tipoproducto')),
            ],
        ),
    ]
