# Generated by Django 4.2 on 2025-06-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoProducto', '0003_alter_tipoproducto_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCultivo', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=32)),
                ('FechaSiembra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=32)),
                ('tipoProductoId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TipoProducto.tipoproducto')),
            ],
            options={
                'db_table': 'producto_producto',
            },
        ),
    ]
