# Generated by Django 4.2 on 2025-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='CantidadDisponible',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='CantidadMinima',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
