# Generated by Django 4.2 on 2025-06-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TipoProducto', '0003_alter_tipoproducto_codigo'),
        ('producto', '0002_producto_cantidaddisponible_producto_cantidadminima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipoProductoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoProducto.tipoproducto'),
        ),
    ]
