# Generated by Django 4.2 on 2025-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_tipoproductoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
