# Generated by Django 4.2 on 2024-09-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_rename_codigo_cliente_id_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_venta', models.CharField(max_length=10, unique=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
