# Generated by Django 4.2 on 2025-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producciones',
            fields=[
                ('Id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_produccion', models.CharField(max_length=32, unique=True)),
                ('calidad_cosecha', models.CharField(max_length=50)),
                ('fecha_produccion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_producida', models.SmallIntegerField()),
                ('lapso_produccion', models.DurationField()),
            ],
        ),
    ]
