# Generated by Django 4.2 on 2025-06-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('producciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producciones',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
    ]
