# Generated by Django 4.2 on 2025-06-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0005_alter_cliente_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_pedido', models.CharField(max_length=6, unique=True)),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=32)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
