# Generated by Django 4.2 on 2024-09-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_pedido',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
