# Generated by Django 4.2 on 2024-09-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidos_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(max_length=32),
        ),
    ]
