# Generated by Django 4.2 on 2025-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('Id_DetalleVenta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_producto', models.SmallIntegerField()),
            ],
        ),
    ]
