# Generated by Django 4.2 on 2025-06-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleVenta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
